### Case study: commitizen
Getting data from Github repo and converted to OCEL2.0 format

In [ ]:
from pystackt import *

from configToken import GITHUB_ACCESS_TOKEN


DUCKDB_PATH_COMMITIZEN =  "raw/commitizen.duckdb"
SQLITE_PATH_COMMITIZEN =  "raw/ocel2_commitizen.sqlite"

from pystackt import get_github_log

get_github_log(
    GITHUB_ACCESS_TOKEN= GITHUB_ACCESS_TOKEN,
    repo_owner="commitizen-tools",
    repo_name="commitizen",
    max_issues=None,
    quack_db=str(DUCKDB_PATH_COMMITIZEN),
    schema="main",
)

In [ ]:
from pystackt import *

export_to_ocel2(
    quack_db= DUCKDB_PATH_COMMITIZEN,
    schema_in="main",
    schema_out="ocel2",
    sqlite_db= SQLITE_PATH_COMMITIZEN
)

In [ ]:
from pystackt import *

create_statistics_views(
    quack_db= DUCKDB_PATH_COMMITIZEN,
    schema_in="main",
    schema_out="statistics"
)

## Finance package #1
TauricResearch
TradingAgents
https://github.com/TauricResearch/TradingAgents

In [34]:
import duckdb
import pandas as pd

from pystackt import *

from configToken import GITHUB_ACCESS_TOKEN

from pathlib import Path
import sys

DUCKDB_PATH_TRADINGAGENTS = "raw/TradingAgents.duckdb"
SQLITE_PATH_TRADINGAGENTS = "raw/TradingAgents.sqlite"

In [ ]:
from pystackt import get_github_log

get_github_log(
    GITHUB_ACCESS_TOKEN= GITHUB_ACCESS_TOKEN,
    repo_owner="TauricResearch",
    repo_name="TradingAgents",
    max_issues=None,
    quack_db= DUCKDB_PATH_TRADINGAGENTS,
    schema="main",
)

Checking if DuckDB database file c:\Users\mahsa.choopannezhadm\OneDrive - University of Liechtenstein\Desktop\PhD materials\codes\Lifecycles-Processes\data\raw\TradingAgents.duckdb is available. New file will be created if it does not exist yet.
    IMPORTANT! Do not connect to DuckDB database file 'c:\Users\mahsa.choopannezhadm\OneDrive - University of Liechtenstein\Desktop\PhD materials\codes\Lifecycles-Processes\data\raw\TradingAgents.duckdb' while this script is running!
    (Or, if you like living on the edge, at least disconnect before the script tries writing to it.)
Start extraction of object-centric event data from all issues of repository TauricResearch/TradingAgents using GitHub REST API via PyGitHub library.
Status updates will be displayed every 1% progress and every 5 minutes. While you wait, you can read about GitHub API rate limits here: https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api
29-07-2026 14:39    Starting data extraction for approximately 1175 issues ...
29-07-2026 14:39    Extracting and mapping data for issue #1175 done ...0.1% (about 2626.0s remaining)
29-07-2026 14:40    Extracting and mapping data for issue #1151 done ...1.0% (about 3690.1s remaining)
29-07-2026 14:40    Extracting and mapping data for issue #1117 done ...2.0% (about 2925.1s remaining)
29-07-2026 14:41    Extracting and mapping data for issue #1099 done ...3.1% (about 2773.2s remaining)
29-07-2026 14:41    Extracting and mapping data for issue #1080 done ...4.0% (about 2933.3s remaining)
29-07-2026 14:42    Extracting and mapping data for issue #1057 done ...5.0% (about 2676.6s remaining)
29-07-2026 14:42    Extracting and mapping data for issue #1042 done ...6.0% (about 2479.5s remaining)
29-07-2026 14:42    Extracting and mapping data for issue #1029 done ...7.1% (about 2338.8s remaining)
29-07-2026 14:43    Extracting and mapping data for issue #1017 done ...8.0% (about 2305.2s remaining)
29-07-2026 14:43    Extracting and mapping data for issue #1005 done ...9.0% (about 2196.3s remaining)
29-07-2026 14:43    Extracting and mapping data for issue #988 done ...10.0% (about 2110.5s remaining)
29-07-2026 14:44    Extracting and mapping data for issue #976 done ...11.1% (about 2029.7s remaining)
29-07-2026 14:44    Extracting and mapping data for issue #955 done ...12.0% (about 1970.4s remaining)
29-07-2026 14:44    Extracting and mapping data for issue #942 done ...13.0% (about 1908.0s remaining)
29-07-2026 14:44    Extracting and mapping data for issue #925 done ...13.9% (about 1870.5s remaining)
29-07-2026 14:44    Extracting and mapping data for issue #921 done ...14.0% (about 1862.9s remaining)
29-07-2026 14:45    Extracting and mapping data for issue #902 done ...15.1% (about 1841.7s remaining)
29-07-2026 14:45    Extracting and mapping data for issue #890 done ...16.0% (about 1802.4s remaining)
29-07-2026 14:45    Extracting and mapping data for issue #873 done ...17.0% (about 1757.1s remaining)
29-07-2026 14:46    Extracting and mapping data for issue #854 done ...18.0% (about 1726.8s remaining)
29-07-2026 14:46    Extracting and mapping data for issue #840 done ...19.1% (about 1695.0s remaining)
29-07-2026 14:46    Extracting and mapping data for issue #828 done ...20.0% (about 1670.3s remaining)
29-07-2026 14:47    Extracting and mapping data for issue #811 done ...21.0% (about 1644.0s remaining)
29-07-2026 14:47    Extracting and mapping data for issue #796 done ...22.0% (about 1606.3s remaining)
29-07-2026 14:47    Extracting and mapping data for issue #778 done ...23.1% (about 1594.9s remaining)
29-07-2026 14:48    Extracting and mapping data for issue #765 done ...24.0% (about 1587.8s remaining)
29-07-2026 14:48    Extracting and mapping data for issue #751 done ...25.0% (about 1590.1s remaining)
29-07-2026 14:49    Extracting and mapping data for issue #737 done ...26.0% (about 1570.9s remaining)
29-07-2026 14:49    Extracting and mapping data for issue #721 done ...27.1% (about 1533.5s remaining)
29-07-2026 14:49    Extracting and mapping data for issue #708 done ...28.0% (about 1518.0s remaining)
29-07-2026 14:49    Extracting and mapping data for issue #697 done ...28.6% (about 1499.4s remaining)
29-07-2026 14:49    Extracting and mapping data for issue #689 done ...29.0% (about 1489.9s remaining)
29-07-2026 14:50    Extracting and mapping data for issue #672 done ...30.0% (about 1462.1s remaining)
29-07-2026 14:50    Extracting and mapping data for issue #653 done ...31.1% (about 1436.3s remaining)
29-07-2026 14:50    Extracting and mapping data for issue #640 done ...32.0% (about 1411.1s remaining)
29-07-2026 14:51    Extracting and mapping data for issue #623 done ...33.0% (about 1383.3s remaining)
29-07-2026 14:51    Extracting and mapping data for issue #606 done ...34.0% (about 1362.6s remaining)
29-07-2026 14:51    Extracting and mapping data for issue #589 done ...35.1% (about 1338.1s remaining)
29-07-2026 14:52    Extracting and mapping data for issue #575 done ...36.0% (about 1318.7s remaining)
29-07-2026 14:52    Extracting and mapping data for issue #562 done ...37.0% (about 1292.3s remaining)
29-07-2026 14:52    Extracting and mapping data for issue #541 done ...38.0% (about 1280.3s remaining)
29-07-2026 14:53    Extracting and mapping data for issue #527 done ...39.1% (about 1270.5s remaining)
29-07-2026 14:53    Extracting and mapping data for issue #509 done ...40.0% (about 1248.6s remaining)
29-07-2026 14:53    Extracting and mapping data for issue #491 done ...41.0% (about 1223.7s remaining)
29-07-2026 14:54    Extracting and mapping data for issue #476 done ...42.0% (about 1199.4s remaining)
29-07-2026 14:54    Extracting and mapping data for issue #460 done ...43.1% (about 1184.8s remaining)
29-07-2026 14:54    Extracting and mapping data for issue #458 done ...43.2% (about 1181.9s remaining)
29-07-2026 14:55    Extracting and mapping data for issue #442 done ...44.0% (about 1164.9s remaining)
29-07-2026 14:55    Extracting and mapping data for issue #418 done ...45.0% (about 1141.1s remaining)
29-07-2026 14:55    Extracting and mapping data for issue #404 done ...46.0% (about 1121.2s remaining)
29-07-2026 14:56    Extracting and mapping data for issue #391 done ...47.1% (about 1099.4s remaining)
29-07-2026 14:56    Extracting and mapping data for issue #380 done ...48.0% (about 1075.5s remaining)
29-07-2026 14:56    Extracting and mapping data for issue #364 done ...49.0% (about 1059.9s remaining)
29-07-2026 14:57    Extracting and mapping data for issue #350 done ...50.0% (about 1035.7s remaining)
29-07-2026 14:57    Extracting and mapping data for issue #334 done ...51.1% (about 1010.4s remaining)
29-07-2026 14:57    Extracting and mapping data for issue #323 done ...52.0% (about 992.1s remaining)
29-07-2026 14:58    Extracting and mapping data for issue #309 done ...53.0% (about 969.3s remaining)
29-07-2026 14:58    Extracting and mapping data for issue #295 done ...54.0% (about 951.0s remaining)
29-07-2026 14:58    Extracting and mapping data for issue #279 done ...55.1% (about 929.2s remaining)
29-07-2026 14:59    Extracting and mapping data for issue #262 done ...56.0% (about 908.3s remaining)
29-07-2026 14:59    Extracting and mapping data for issue #245 done ...57.0% (about 887.3s remaining)
29-07-2026 14:59    Extracting and mapping data for issue #223 done ...58.0% (about 868.1s remaining)
29-07-2026 15:00    Extracting and mapping data for issue #200 done ...59.1% (about 846.5s remaining)
29-07-2026 15:00    Extracting and mapping data for issue #179 done ...60.0% (about 825.7s remaining)
29-07-2026 15:00    Extracting and mapping data for issue #142 done ...61.0% (about 803.4s remaining)
29-07-2026 15:01    Extracting and mapping data for issue #114 done ...62.0% (about 782.5s remaining)
29-07-2026 15:01    Extracting and mapping data for issue #102 done ...63.1% (about 761.9s remaining)
29-07-2026 15:01    Extracting and mapping data for issue #89 done ...64.0% (about 744.6s remaining)
29-07-2026 15:02    Extracting and mapping data for issue #75 done ...65.0% (about 724.9s remaining)
29-07-2026 15:02    Extracting and mapping data for issue #62 done ...66.0% (about 706.5s remaining)
29-07-2026 15:02    Extracting and mapping data for issue #46 done ...67.1% (about 683.8s remaining)
29-07-2026 15:03    Extracting and mapping data for issue #35 done ...68.0% (about 662.1s remaining)
29-07-2026 15:03    Extracting and mapping data for issue #21 done ...69.0% (about 639.2s remaining)
29-07-2026 15:03    Extracting and mapping data for issue #8 done ...70.0% (about 616.8s remaining)
29-07-2026 15:04    Data extraction done! (Final percentage can differ from 100% since it's calculated based on the initial estimate of the number of issues.)
29-07-2026 15:04    Saving object-centric event data extracted from TauricResearch/TradingAgents to DuckDB database file c:\Users\mahsa.choopannezhadm\OneDrive - University of Liechtenstein\Desktop\PhD materials\codes\Lifecycles-Processes\data\raw\TradingAgents.duckdb, schema main.
Cannot drop schema "main" because it is an internal system entry
    Table object_types (4 records) done.
    Table object_attributes (15 records) done.
    Table objects (9701 records) done.
    Table object_attribute_values (28786 records) done.
    Table event_types (28 records) done.
    Table events (14059 records) done.
    Table event_attributes (28 records) done.
    Table event_attribute_values (2492 records) done.
    Table relation_qualifiers (7 records) done.
    Table event_to_object (35694 records) done.
    Table object_to_object (848 records) done.
    Table event_to_object_attribute_value (0 records) done.
29-07-2026 15:04    All done!

In [35]:
from pystackt import export_to_ocel2

export_to_ocel2(
    quack_db= DUCKDB_PATH_TRADINGAGENTS,
    schema_in="main",
    schema_out="ocel2",
    sqlite_db= SQLITE_PATH_TRADINGAGENTS
)

Overwriting schema 'ocel2'
    creating OCEL 2.0 table 'event'
    creating OCEL 2.0 table 'event_map_type'
    creating OCEL 2.0 table 'event_object'
    creating OCEL 2.0 table 'object_object'
    creating OCEL 2.0 table 'object'
    creating OCEL 2.0 table 'object_map_type'
    creating OCEL 2.0 table 'event_created'
    creating OCEL 2.0 table 'event_committed'
    creating OCEL 2.0 table 'event_commented'
    creating OCEL 2.0 table 'event_closed'
    creating OCEL 2.0 table 'event_renamed'
    creating OCEL 2.0 table 'event_head_ref_deleted'
    creating OCEL 2.0 table 'event_reviewed'
    creating OCEL 2.0 table 'event_referenced'
    creating OCEL 2.0 table 'event_cross_referenced'
    creating OCEL 2.0 table 'event_mentioned'
    creating OCEL 2.0 table 'event_subscribed'
    creating OCEL 2.0 table 'event_head_ref_force_pushed'
    creating OCEL 2.0 table 'event_unsubscribed'
    creating OCEL 2.0 table 'event_convert_to_draft'
    creating OCEL 2.0 table 'event_ready_for_review'
    creating OCEL 2.0 table 'event_head_ref_restored'
    creating OCEL 2.0 table 'event_reopened'
    creating OCEL 2.0 table 'event_review_requested'
    creating OCEL 2.0 table 'event_copilot_work_started'
    creating OCEL 2.0 table 'event_merged'
    creating OCEL 2.0 table 'event_comment_deleted'
    creating OCEL 2.0 table 'event_review_dismissed'
    creating OCEL 2.0 table 'event_base_ref_changed'
    creating OCEL 2.0 table 'event_base_ref_deleted'
    creating OCEL 2.0 table 'event_labeled'
    creating OCEL 2.0 table 'event_assigned'
    creating OCEL 2.0 table 'event_issue_type_added'
    creating OCEL 2.0 table 'event_unlabeled'
    creating OCEL 2.0 table 'object_issue'
    creating OCEL 2.0 table 'object_user'
    creating OCEL 2.0 table 'object_team'
    creating OCEL 2.0 table 'object_commit'
Exporting 'ocel2' from raw/TradingAgents.duckdb to raw/TradingAgents.sqlite...
All done!

In [36]:
from pystackt import create_statistics_views

create_statistics_views(
    quack_db= DUCKDB_PATH_TRADINGAGENTS,
    schema_in="main",
    schema_out="statistics"
)

Overwriting schema 'statistics'
All done! You can explore the statistics on the OCED in schema main, using the views located in schema statistics of your DuckDB database file raw/TradingAgents.duckdb.

In [ ]:
from pystackt import *

prepare_graph_data(
    quack_db= DUCKDB_PATH_TRADINGAGENTS,
    schema_in="main",
    schema_out="graph_data_prep"
)

start_visualization_app(
    quack_db= DUCKDB_PATH_TRADINGAGENTS,
    schema="graph_data_prep"
)

In [38]:
import duckdb

quack_db = DUCKDB_PATH_TRADINGAGENTS

with duckdb.connect(quack_db, read_only=True) as con:
    eventsPerobj_df = con.sql("SELECT * FROM graph_data_prep.graph_base_table").df()

eventsPerobj_df

,event_node_id,event_id,event_description,event_type_id,event_type,event_timestamp,event_timestamp_node_id,snapshot_node_id,object_id,object_description,object_type_id,object_type,snapshot_timestamp,snapshot_timestamp_node_id,qualifier_id,qualifier_description,snapshot_dense_rank
0,event_32,32,create #1175,31,created,2026-07-26 05:38:45,2026-07-26 05:38:45,object_36_2026-07-26 05:38:45,36,user:108789129,2,user,2026-07-26 05:38:45,2026-07-26 05:38:45,21,created,1
1,event_179,179,closed (#1175),178,closed,2026-07-26 05:39:05,2026-07-26 05:39:05,object_36_2026-07-26 05:39:05,36,user:108789129,2,user,2026-07-26 05:39:05,2026-07-26 05:39:05,22,actor,2
2,event_184,184,renamed (#1175),183,renamed,2026-07-26 05:46:10,2026-07-26 05:46:10,object_36_2026-07-26 05:46:10,36,user:108789129,2,user,2026-07-26 05:46:10,2026-07-26 05:46:10,22,actor,3
3,event_539,539,committed (#1172),43,committed,2026-06-22 19:26:11,2026-06-22 19:26:11,object_541_2026-06-22 19:26:11,541,sha:00ee4d21b9c37e34f737857e27d511c7136651d3,4,commit,2026-06-22 19:26:11,2026-06-22 19:26:11,20,timeline_event,1
4,event_695,695,committed (#1165),43,committed,2026-07-07 18:47:55,2026-07-07 18:47:55,object_697_2026-07-07 18:47:55,697,sha:1259a7b4e1524b1c97935619b7db40d136ba54a7,4,commit,2026-07-07 18:47:55,2026-07-07 18:47:55,20,timeline_event,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35689,event_86739,86739,commented (#75),167,commented,2025-07-02 05:40:52,2025-07-02 05:40:52,object_86064_2025-07-02 05:40:52,86064,user:24488576,2,user,2025-07-02 05:40:52,2025-07-02 05:40:52,22,actor,2
35690,event_86061,86061,commented (#88),167,commented,2025-07-04 02:35:41,2025-07-04 02:35:41,object_86064_2025-07-04 02:35:41,86064,user:24488576,2,user,2025-07-04 02:35:41,2025-07-04 02:35:41,22,actor,3
35691,event_87948,87948,commented (#68),167,commented,2025-07-05 13:20:53,2025-07-05 13:20:53,object_86064_2025-07-05 13:20:53,86064,user:24488576,2,user,2025-07-05 13:20:53,2025-07-05 13:20:53,22,actor,4
35692,event_86262,86262,committed (#85),43,committed,2025-06-26 07:52:56,2025-06-26 07:52:56,object_86264_2025-06-26 07:52:56,86264,sha:681dc66fd2ed5007b9f1ca9a6afb94d276965b2b,4,commit,2025-06-26 07:52:56,2025-06-26 07:52:56,20,timeline_event,1
35693,event_86270,86270,committed (#85),43,committed,2025-06-26 08:03:25,2025-06-26 08:03:25,object_86272_2025-06-26 08:03:25,86272,sha:e62672768d9ff6276ba623d347a4af1a5b7dd582,4,commit,2025-06-26 08:03:25,2025-06-26 08:03:25,20,timeline_event,1

## Finance package #2
AI4Finance-Foundation
FinGPT
https://github.com/AI4Finance-Foundation/FinGPT

In [39]:
import duckdb
import pandas as pd

from pystackt import *

from configToken import GITHUB_ACCESS_TOKEN

from pathlib import Path
import sys

DUCKDB_PATH_FINGPT = "raw/FinGPT.duckdb"
SQLITE_PATH_FINGPT = "raw/FinGPT.sqlite"

In [40]:
from pystackt import get_github_log

get_github_log(
    GITHUB_ACCESS_TOKEN= GITHUB_ACCESS_TOKEN,
    repo_owner="AI4Finance-Foundation",
    repo_name="FinGPT",
    max_issues=None,
    quack_db= DUCKDB_PATH_FINGPT,
    schema="main",
)

Checking if DuckDB database file raw/FinGPT.duckdb is available. New file will be created if it does not exist yet.
    IMPORTANT! Do not connect to DuckDB database file 'raw/FinGPT.duckdb' while this script is running!
    (Or, if you like living on the edge, at least disconnect before the script tries writing to it.)
Start extraction of object-centric event data from all issues of repository AI4Finance-Foundation/FinGPT using GitHub REST API via PyGitHub library.
Status updates will be displayed every 1% progress and every 5 minutes. While you wait, you can read about GitHub API rate limits here: https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api
30-07-2026 12:03    Starting data extraction for approximately 261 issues ...
30-07-2026 12:03    Extracting and mapping data for issue #261 done ...0.4% (about 477.7s remaining)
30-07-2026 12:03    Extracting and mapping data for issue #259 done ...1.1% (about 378.7s remaining)
30-07-2026 12:04    Extracting and mapping data for issue #256 done ...2.3% (about 398.6s remaining)
30-07-2026 12:04    Extracting and mapping data for issue #244 done ...3.1% (about 383.5s remaining)
30-07-2026 12:04    Extracting and mapping data for issue #241 done ...4.2% (about 431.1s remaining)
30-07-2026 12:04    Extracting and mapping data for issue #230 done ...5.4% (about 413.7s remaining)
30-07-2026 12:04    Extracting and mapping data for issue #227 done ...6.1% (about 403.1s remaining)
30-07-2026 12:04    Extracting and mapping data for issue #221 done ...7.3% (about 401.7s remaining)
30-07-2026 12:04    Extracting and mapping data for issue #218 done ...8.0% (about 392.0s remaining)
30-07-2026 12:04    Extracting and mapping data for issue #208 done ...9.2% (about 398.4s remaining)
30-07-2026 12:04    Extracting and mapping data for issue #203 done ...10.3% (about 394.0s remaining)
30-07-2026 12:04    Extracting and mapping data for issue #200 done ...11.1% (about 391.3s remaining)
30-07-2026 12:04    Extracting and mapping data for issue #195 done ...12.3% (about 389.8s remaining)
30-07-2026 12:04    Extracting and mapping data for issue #192 done ...13.0% (about 385.9s remaining)
30-07-2026 12:04    Extracting and mapping data for issue #180 done ...14.2% (about 378.1s remaining)
30-07-2026 12:05    Extracting and mapping data for issue #174 done ...15.3% (about 368.3s remaining)
30-07-2026 12:05    Extracting and mapping data for issue #168 done ...16.1% (about 362.5s remaining)
30-07-2026 12:05    Extracting and mapping data for issue #161 done ...17.2% (about 390.4s remaining)
30-07-2026 12:05    Extracting and mapping data for issue #155 done ...18.0% (about 381.4s remaining)
30-07-2026 12:05    Extracting and mapping data for issue #148 done ...19.2% (about 374.2s remaining)
30-07-2026 12:05    Extracting and mapping data for issue #139 done ...20.3% (about 364.1s remaining)
30-07-2026 12:05    Extracting and mapping data for issue #131 done ...21.1% (about 358.5s remaining)
30-07-2026 12:05    Extracting and mapping data for issue #128 done ...22.2% (about 348.1s remaining)
30-07-2026 12:05    Extracting and mapping data for issue #122 done ...23.4% (about 342.8s remaining)
30-07-2026 12:05    Extracting and mapping data for issue #117 done ...24.1% (about 337.6s remaining)
30-07-2026 12:05    Extracting and mapping data for issue #114 done ...25.3% (about 331.9s remaining)
30-07-2026 12:05    Extracting and mapping data for issue #110 done ...26.1% (about 326.9s remaining)
30-07-2026 12:05    Extracting and mapping data for issue #106 done ...27.2% (about 321.4s remaining)
30-07-2026 12:06    Extracting and mapping data for issue #102 done ...28.4% (about 315.9s remaining)
30-07-2026 12:06    Extracting and mapping data for issue #98 done ...29.1% (about 312.6s remaining)
30-07-2026 12:06    Extracting and mapping data for issue #95 done ...30.3% (about 305.7s remaining)
30-07-2026 12:06    Extracting and mapping data for issue #93 done ...31.0% (about 301.4s remaining)
30-07-2026 12:06    Extracting and mapping data for issue #89 done ...32.2% (about 294.8s remaining)
30-07-2026 12:06    Extracting and mapping data for issue #77 done ...33.3% (about 290.0s remaining)
30-07-2026 12:06    Extracting and mapping data for issue #70 done ...34.1% (about 288.9s remaining)
30-07-2026 12:06    Extracting and mapping data for issue #59 done ...35.2% (about 284.7s remaining)
30-07-2026 12:06    Extracting and mapping data for issue #51 done ...36.0% (about 281.4s remaining)
30-07-2026 12:06    Extracting and mapping data for issue #38 done ...37.2% (about 274.6s remaining)
30-07-2026 12:06    Extracting and mapping data for issue #29 done ...38.3% (about 270.0s remaining)
30-07-2026 12:06    Extracting and mapping data for issue #27 done ...39.1% (about 265.3s remaining)
30-07-2026 12:06    Extracting and mapping data for issue #24 done ...40.2% (about 258.5s remaining)
30-07-2026 12:06    Extracting and mapping data for issue #21 done ...41.4% (about 251.8s remaining)
30-07-2026 12:06    Extracting and mapping data for issue #18 done ...42.1% (about 247.8s remaining)
30-07-2026 12:06    Extracting and mapping data for issue #12 done ...43.3% (about 242.0s remaining)
30-07-2026 12:07    Extracting and mapping data for issue #10 done ...44.1% (about 237.6s remaining)
30-07-2026 12:07    Extracting and mapping data for issue #6 done ...45.2% (about 231.5s remaining)
30-07-2026 12:07    Data extraction done! (Final percentage can differ from 100% since it's calculated based on the initial estimate of the number of issues.)
30-07-2026 12:07    Saving object-centric event data extracted from AI4Finance-Foundation/FinGPT to DuckDB database file raw/FinGPT.duckdb, schema main.
Cannot drop schema "main" because it is an internal system entry
    Table object_types (4 records) done.
    Table object_attributes (15 records) done.
    Table objects (776 records) done.
    Table object_attribute_values (2318 records) done.
    Table event_types (20 records) done.
    Table events (1139 records) done.
    Table event_attributes (20 records) done.
    Table event_attribute_values (253 records) done.
    Table relation_qualifiers (7 records) done.
    Table event_to_object (2809 records) done.
    Table object_to_object (147 records) done.
    Table event_to_object_attribute_value (0 records) done.
30-07-2026 12:07    All done!

In [42]:
from pystackt import export_to_ocel2

export_to_ocel2(
    quack_db= DUCKDB_PATH_FINGPT,
    schema_in="main",
    schema_out="ocel2",
    sqlite_db= SQLITE_PATH_FINGPT
)

Overwriting schema 'ocel2'
    creating OCEL 2.0 table 'event'
    creating OCEL 2.0 table 'event_map_type'
    creating OCEL 2.0 table 'event_object'
    creating OCEL 2.0 table 'object_object'
    creating OCEL 2.0 table 'object'
    creating OCEL 2.0 table 'object_map_type'
    creating OCEL 2.0 table 'event_created'
    creating OCEL 2.0 table 'event_committed'
    creating OCEL 2.0 table 'event_assigned'
    creating OCEL 2.0 table 'event_merged'
    creating OCEL 2.0 table 'event_closed'
    creating OCEL 2.0 table 'event_head_ref_deleted'
    creating OCEL 2.0 table 'event_review_requested'
    creating OCEL 2.0 table 'event_head_ref_force_pushed'
    creating OCEL 2.0 table 'event_mentioned'
    creating OCEL 2.0 table 'event_subscribed'
    creating OCEL 2.0 table 'event_comment_deleted'
    creating OCEL 2.0 table 'event_commented'
    creating OCEL 2.0 table 'event_unsubscribed'
    creating OCEL 2.0 table 'event_cross_referenced'
    creating OCEL 2.0 table 'event_renamed'
    creating OCEL 2.0 table 'event_reviewed'
    creating OCEL 2.0 table 'event_referenced'
    creating OCEL 2.0 table 'event_reopened'
    creating OCEL 2.0 table 'event_head_ref_restored'
    creating OCEL 2.0 table 'event_labeled'
    creating OCEL 2.0 table 'object_issue'
    creating OCEL 2.0 table 'object_user'
    creating OCEL 2.0 table 'object_team'
    creating OCEL 2.0 table 'object_commit'
Exporting 'ocel2' from raw/FinGPT.duckdb to raw/FinGPT.sqlite...
All done!

In [44]:
from pystackt import create_statistics_views

create_statistics_views(
    quack_db= DUCKDB_PATH_FINGPT,
    schema_in="main",
    schema_out="statistics"
)

Overwriting schema 'statistics'
All done! You can explore the statistics on the OCED in schema main, using the views located in schema statistics of your DuckDB database file raw/FinGPT.duckdb.

In [ ]:
from pystackt import *

prepare_graph_data(
    quack_db= DUCKDB_PATH_FINGPT,
    schema_in="main",
    schema_out="graph_data_prep"
)

start_visualization_app(
    quack_db= DUCKDB_PATH_FINGPT,
    schema="graph_data_prep"
)

In [49]:
import duckdb

quack_db = DUCKDB_PATH_TRADINGAGENTS

with duckdb.connect(quack_db, read_only=True) as con:
    eventsPerobj_df = con.sql("SELECT * FROM graph_data_prep.graph_base_table").df()

eventsPerobj_df

,event_node_id,event_id,event_description,event_type_id,event_type,event_timestamp,event_timestamp_node_id,snapshot_node_id,object_id,object_description,object_type_id,object_type,snapshot_timestamp,snapshot_timestamp_node_id,qualifier_id,qualifier_description,snapshot_dense_rank
0,event_32,32,create #1175,31,created,2026-07-26 05:38:45,2026-07-26 05:38:45,object_36_2026-07-26 05:38:45,36,user:108789129,2,user,2026-07-26 05:38:45,2026-07-26 05:38:45,21,created,1
1,event_179,179,closed (#1175),178,closed,2026-07-26 05:39:05,2026-07-26 05:39:05,object_36_2026-07-26 05:39:05,36,user:108789129,2,user,2026-07-26 05:39:05,2026-07-26 05:39:05,22,actor,2
2,event_184,184,renamed (#1175),183,renamed,2026-07-26 05:46:10,2026-07-26 05:46:10,object_36_2026-07-26 05:46:10,36,user:108789129,2,user,2026-07-26 05:46:10,2026-07-26 05:46:10,22,actor,3
3,event_539,539,committed (#1172),43,committed,2026-06-22 19:26:11,2026-06-22 19:26:11,object_541_2026-06-22 19:26:11,541,sha:00ee4d21b9c37e34f737857e27d511c7136651d3,4,commit,2026-06-22 19:26:11,2026-06-22 19:26:11,20,timeline_event,1
4,event_695,695,committed (#1165),43,committed,2026-07-07 18:47:55,2026-07-07 18:47:55,object_697_2026-07-07 18:47:55,697,sha:1259a7b4e1524b1c97935619b7db40d136ba54a7,4,commit,2026-07-07 18:47:55,2026-07-07 18:47:55,20,timeline_event,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35689,event_86739,86739,commented (#75),167,commented,2025-07-02 05:40:52,2025-07-02 05:40:52,object_86064_2025-07-02 05:40:52,86064,user:24488576,2,user,2025-07-02 05:40:52,2025-07-02 05:40:52,22,actor,2
35690,event_86061,86061,commented (#88),167,commented,2025-07-04 02:35:41,2025-07-04 02:35:41,object_86064_2025-07-04 02:35:41,86064,user:24488576,2,user,2025-07-04 02:35:41,2025-07-04 02:35:41,22,actor,3
35691,event_87948,87948,commented (#68),167,commented,2025-07-05 13:20:53,2025-07-05 13:20:53,object_86064_2025-07-05 13:20:53,86064,user:24488576,2,user,2025-07-05 13:20:53,2025-07-05 13:20:53,22,actor,4
35692,event_86262,86262,committed (#85),43,committed,2025-06-26 07:52:56,2025-06-26 07:52:56,object_86264_2025-06-26 07:52:56,86264,sha:681dc66fd2ed5007b9f1ca9a6afb94d276965b2b,4,commit,2025-06-26 07:52:56,2025-06-26 07:52:56,20,timeline_event,1
35693,event_86270,86270,committed (#85),43,committed,2025-06-26 08:03:25,2025-06-26 08:03:25,object_86272_2025-06-26 08:03:25,86272,sha:e62672768d9ff6276ba623d347a4af1a5b7dd582,4,commit,2025-06-26 08:03:25,2025-06-26 08:03:25,20,timeline_event,1

## Finance package #3
HKUDS
Vibe-Trading
https://github.com/HKUDS/Vibe-Trading

In [47]:
import duckdb
import pandas as pd

from pystackt import *

from configToken import GITHUB_ACCESS_TOKEN

from pathlib import Path
import sys

DUCKDB_PATH_VIBETRADING = "raw/Vibe-Trading.duckdb"
SQLITE_PATH_VIBETRADING = "raw/Vibe-Trading.sqlite"

In [51]:
from pystackt import get_github_log

get_github_log(
    GITHUB_ACCESS_TOKEN= GITHUB_ACCESS_TOKEN,
    repo_owner="HKUDS",
    repo_name="Vibe-Trading",
    max_issues=None,
    quack_db= DUCKDB_PATH_VIBETRADING,
    schema="main",
)

Checking if DuckDB database file raw/Vibe-Trading.duckdb is available. New file will be created if it does not exist yet.
    IMPORTANT! Do not connect to DuckDB database file 'raw/Vibe-Trading.duckdb' while this script is running!
    (Or, if you like living on the edge, at least disconnect before the script tries writing to it.)
Start extraction of object-centric event data from all issues of repository HKUDS/Vibe-Trading using GitHub REST API via PyGitHub library.
Status updates will be displayed every 1% progress and every 5 minutes. While you wait, you can read about GitHub API rate limits here: https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api
30-07-2026 12:28    Starting data extraction for approximately 914 issues ...
30-07-2026 12:28    Extracting and mapping data for issue #914 done ...0.1% (about 7932.1s remaining)
30-07-2026 12:29    Extracting and mapping data for issue #901 done ...1.1% (about 5702.5s remaining)
30-07-2026 12:29    Extracting and mapping data for issue #884 done ...2.1% (about 3607.4s remaining)
30-07-2026 12:29    Extracting and mapping data for issue #874 done ...3.1% (about 2860.6s remaining)
30-07-2026 12:29    Extracting and mapping data for issue #864 done ...4.0% (about 2467.9s remaining)
30-07-2026 12:29    Extracting and mapping data for issue #855 done ...5.0% (about 2222.0s remaining)
30-07-2026 12:30    Extracting and mapping data for issue #846 done ...6.0% (about 2160.3s remaining)
30-07-2026 12:30    Extracting and mapping data for issue #836 done ...7.0% (about 2027.5s remaining)
30-07-2026 12:30    Extracting and mapping data for issue #826 done ...8.1% (about 1892.2s remaining)
30-07-2026 12:31    Extracting and mapping data for issue #816 done ...9.1% (about 1934.5s remaining)
30-07-2026 12:31    Extracting and mapping data for issue #807 done ...10.1% (about 1855.3s remaining)
30-07-2026 12:31    Extracting and mapping data for issue #798 done ...11.1% (about 1773.9s remaining)
30-07-2026 12:31    Extracting and mapping data for issue #789 done ...12.0% (about 1701.1s remaining)
30-07-2026 12:32    Extracting and mapping data for issue #780 done ...13.0% (about 1638.3s remaining)
30-07-2026 12:32    Extracting and mapping data for issue #771 done ...14.0% (about 1591.3s remaining)
30-07-2026 12:32    Extracting and mapping data for issue #761 done ...15.1% (about 1533.3s remaining)
30-07-2026 12:32    Extracting and mapping data for issue #749 done ...16.1% (about 1520.5s remaining)
30-07-2026 12:33    Extracting and mapping data for issue #743 done ...16.7% (about 1494.8s remaining)
30-07-2026 12:33    Extracting and mapping data for issue #740 done ...17.1% (about 1481.1s remaining)
30-07-2026 12:33    Extracting and mapping data for issue #731 done ...18.1% (about 1453.0s remaining)
30-07-2026 12:33    Extracting and mapping data for issue #722 done ...19.0% (about 1417.7s remaining)
30-07-2026 12:33    Extracting and mapping data for issue #713 done ...20.0% (about 1387.0s remaining)
30-07-2026 12:34    Extracting and mapping data for issue #701 done ...21.0% (about 1353.1s remaining)
30-07-2026 12:34    Extracting and mapping data for issue #691 done ...22.1% (about 1346.9s remaining)
30-07-2026 12:34    Extracting and mapping data for issue #682 done ...23.1% (about 1319.2s remaining)
30-07-2026 12:35    Extracting and mapping data for issue #673 done ...24.1% (about 1337.6s remaining)
30-07-2026 12:35    Extracting and mapping data for issue #664 done ...25.1% (about 1306.0s remaining)
30-07-2026 12:35    Extracting and mapping data for issue #655 done ...26.0% (about 1313.1s remaining)
30-07-2026 12:35    Extracting and mapping data for issue #646 done ...27.0% (about 1284.3s remaining)
30-07-2026 12:36    Extracting and mapping data for issue #637 done ...28.0% (about 1257.8s remaining)
30-07-2026 12:36    Extracting and mapping data for issue #627 done ...29.1% (about 1227.6s remaining)
30-07-2026 12:36    Extracting and mapping data for issue #618 done ...30.1% (about 1201.3s remaining)
30-07-2026 12:36    Extracting and mapping data for issue #609 done ...31.1% (about 1174.9s remaining)
30-07-2026 12:37    Extracting and mapping data for issue #600 done ...32.1% (about 1150.5s remaining)
30-07-2026 12:37    Extracting and mapping data for issue #591 done ...33.0% (about 1129.5s remaining)
30-07-2026 12:37    Extracting and mapping data for issue #582 done ...34.0% (about 1108.6s remaining)
30-07-2026 12:37    Extracting and mapping data for issue #573 done ...35.0% (about 1086.3s remaining)
30-07-2026 12:38    Extracting and mapping data for issue #564 done ...36.0% (about 1067.0s remaining)
30-07-2026 12:38    Extracting and mapping data for issue #563 done ...36.1% (about 1064.8s remaining)
30-07-2026 12:38    Extracting and mapping data for issue #553 done ...37.1% (about 1045.4s remaining)
30-07-2026 12:38    Extracting and mapping data for issue #544 done ...38.1% (about 1027.9s remaining)
30-07-2026 12:38    Extracting and mapping data for issue #534 done ...39.1% (about 1011.3s remaining)
30-07-2026 12:39    Extracting and mapping data for issue #525 done ...40.0% (about 992.4s remaining)
30-07-2026 12:39    Extracting and mapping data for issue #516 done ...41.0% (about 973.4s remaining)
30-07-2026 12:39    Extracting and mapping data for issue #507 done ...42.0% (about 954.3s remaining)
30-07-2026 12:39    Extracting and mapping data for issue #497 done ...43.1% (about 932.9s remaining)
30-07-2026 12:40    Extracting and mapping data for issue #488 done ...44.1% (about 914.1s remaining)
30-07-2026 12:40    Extracting and mapping data for issue #478 done ...45.1% (about 896.4s remaining)
30-07-2026 12:40    Extracting and mapping data for issue #467 done ...46.1% (about 879.5s remaining)
30-07-2026 12:40    Extracting and mapping data for issue #457 done ...47.0% (about 860.2s remaining)
30-07-2026 12:41    Extracting and mapping data for issue #448 done ...48.0% (about 843.1s remaining)
30-07-2026 12:41    Extracting and mapping data for issue #438 done ...49.0% (about 832.1s remaining)
30-07-2026 12:41    Extracting and mapping data for issue #429 done ...50.0% (about 814.1s remaining)
30-07-2026 12:41    Extracting and mapping data for issue #418 done ...51.1% (about 792.8s remaining)
30-07-2026 12:42    Extracting and mapping data for issue #409 done ...52.1% (about 777.1s remaining)
30-07-2026 12:42    Extracting and mapping data for issue #400 done ...53.1% (about 760.1s remaining)
30-07-2026 12:42    Extracting and mapping data for issue #391 done ...54.0% (about 742.0s remaining)
30-07-2026 12:42    Extracting and mapping data for issue #381 done ...55.0% (about 724.8s remaining)
30-07-2026 12:43    Extracting and mapping data for issue #373 done ...55.9% (about 711.2s remaining)
30-07-2026 12:43    Extracting and mapping data for issue #372 done ...56.0% (about 709.4s remaining)
30-07-2026 12:43    Extracting and mapping data for issue #362 done ...57.0% (about 691.4s remaining)
30-07-2026 12:43    Extracting and mapping data for issue #352 done ...58.1% (about 670.4s remaining)
30-07-2026 12:43    Extracting and mapping data for issue #343 done ...59.1% (about 652.7s remaining)
30-07-2026 12:43    Extracting and mapping data for issue #333 done ...60.1% (about 636.5s remaining)
30-07-2026 12:44    Extracting and mapping data for issue #324 done ...61.1% (about 620.6s remaining)
30-07-2026 12:44    Extracting and mapping data for issue #315 done ...62.0% (about 603.3s remaining)
30-07-2026 12:44    Extracting and mapping data for issue #306 done ...63.0% (about 587.2s remaining)
30-07-2026 12:44    Extracting and mapping data for issue #297 done ...64.0% (about 570.7s remaining)
30-07-2026 12:45    Extracting and mapping data for issue #286 done ...65.1% (about 552.2s remaining)
30-07-2026 12:45    Extracting and mapping data for issue #277 done ...66.1% (about 536.5s remaining)
30-07-2026 12:45    Extracting and mapping data for issue #267 done ...67.1% (about 519.9s remaining)
30-07-2026 12:45    Extracting and mapping data for issue #257 done ...68.1% (about 503.6s remaining)
30-07-2026 12:46    Extracting and mapping data for issue #248 done ...69.0% (about 488.5s remaining)
30-07-2026 12:46    Extracting and mapping data for issue #239 done ...70.0% (about 472.0s remaining)
30-07-2026 12:46    Extracting and mapping data for issue #230 done ...71.0% (about 455.2s remaining)
30-07-2026 12:46    Extracting and mapping data for issue #219 done ...72.1% (about 437.3s remaining)
30-07-2026 12:47    Extracting and mapping data for issue #210 done ...73.1% (about 421.6s remaining)
30-07-2026 12:47    Extracting and mapping data for issue #201 done ...74.1% (about 405.7s remaining)
30-07-2026 12:47    Extracting and mapping data for issue #192 done ...75.1% (about 390.1s remaining)
30-07-2026 12:47    Extracting and mapping data for issue #183 done ...76.0% (about 374.6s remaining)
30-07-2026 12:48    Extracting and mapping data for issue #178 done ...76.6% (about 366.9s remaining)
30-07-2026 12:48    Extracting and mapping data for issue #174 done ...77.0% (about 359.9s remaining)
30-07-2026 12:48    Extracting and mapping data for issue #164 done ...78.0% (about 344.4s remaining)
30-07-2026 12:48    Extracting and mapping data for issue #149 done ...79.1% (about 327.1s remaining)
30-07-2026 12:48    Extracting and mapping data for issue #138 done ...80.1% (about 311.2s remaining)
30-07-2026 12:49    Extracting and mapping data for issue #129 done ...81.1% (about 295.5s remaining)
30-07-2026 12:49    Extracting and mapping data for issue #120 done ...82.1% (about 279.9s remaining)
30-07-2026 12:49    Extracting and mapping data for issue #111 done ...83.0% (about 264.5s remaining)
30-07-2026 12:49    Extracting and mapping data for issue #101 done ...84.0% (about 249.0s remaining)
30-07-2026 12:50    Extracting and mapping data for issue #91 done ...85.0% (about 233.4s remaining)
30-07-2026 12:50    Extracting and mapping data for issue #80 done ...86.1% (about 216.5s remaining)
30-07-2026 12:50    Extracting and mapping data for issue #71 done ...87.1% (about 201.0s remaining)
30-07-2026 12:50    Extracting and mapping data for issue #61 done ...88.1% (about 185.6s remaining)
30-07-2026 12:51    Extracting and mapping data for issue #50 done ...89.1% (about 170.3s remaining)
30-07-2026 12:51    Extracting and mapping data for issue #41 done ...90.0% (about 154.9s remaining)
30-07-2026 12:51    Extracting and mapping data for issue #32 done ...91.0% (about 139.5s remaining)
30-07-2026 12:51    Extracting and mapping data for issue #19 done ...92.0% (about 124.2s remaining)
30-07-2026 12:52    Extracting and mapping data for issue #9 done ...93.1% (about 106.9s remaining)
30-07-2026 12:52    Data extraction done! (Final percentage can differ from 100% since it's calculated based on the initial estimate of the number of issues.)
30-07-2026 12:52    Saving object-centric event data extracted from HKUDS/Vibe-Trading to DuckDB database file raw/Vibe-Trading.duckdb, schema main.
Cannot drop schema "main" because it is an internal system entry
    Table object_types (4 records) done.
    Table object_attributes (15 records) done.
    Table objects (7167 records) done.
    Table object_attribute_values (21286 records) done.
    Table event_types (26 records) done.
    Table events (12905 records) done.
    Table event_attributes (26 records) done.
    Table event_attribute_values (1926 records) done.
    Table relation_qualifiers (7 records) done.
    Table event_to_object (31678 records) done.
    Table object_to_object (876 records) done.
    Table event_to_object_attribute_value (0 records) done.
30-07-2026 12:52    All done!

In [52]:
from pystackt import export_to_ocel2

export_to_ocel2(
    quack_db= DUCKDB_PATH_VIBETRADING,
    schema_in="main",
    schema_out="ocel2",
    sqlite_db= SQLITE_PATH_VIBETRADING
)

Overwriting schema 'ocel2'
    creating OCEL 2.0 table 'event'
    creating OCEL 2.0 table 'event_map_type'
    creating OCEL 2.0 table 'event_object'
    creating OCEL 2.0 table 'object_object'
    creating OCEL 2.0 table 'object'
    creating OCEL 2.0 table 'object_map_type'
    creating OCEL 2.0 table 'event_created'
    creating OCEL 2.0 table 'event_committed'
    creating OCEL 2.0 table 'event_base_ref_force_pushed'
    creating OCEL 2.0 table 'event_cross_referenced'
    creating OCEL 2.0 table 'event_commented'
    creating OCEL 2.0 table 'event_closed'
    creating OCEL 2.0 table 'event_referenced'
    creating OCEL 2.0 table 'event_head_ref_force_pushed'
    creating OCEL 2.0 table 'event_reviewed'
    creating OCEL 2.0 table 'event_merged'
    creating OCEL 2.0 table 'event_head_ref_deleted'
    creating OCEL 2.0 table 'event_labeled'
    creating OCEL 2.0 table 'event_renamed'
    creating OCEL 2.0 table 'event_mentioned'
    creating OCEL 2.0 table 'event_subscribed'
    creating OCEL 2.0 table 'event_unsubscribed'
    creating OCEL 2.0 table 'event_locked'
    creating OCEL 2.0 table 'event_unlocked'
    creating OCEL 2.0 table 'event_review_requested'
    creating OCEL 2.0 table 'event_ready_for_review'
    creating OCEL 2.0 table 'event_head_ref_restored'
    creating OCEL 2.0 table 'event_convert_to_draft'
    creating OCEL 2.0 table 'event_reopened'
    creating OCEL 2.0 table 'event_copilot_work_started'
    creating OCEL 2.0 table 'event_unlabeled'
    creating OCEL 2.0 table 'event_comment_deleted'
    creating OCEL 2.0 table 'object_issue'
    creating OCEL 2.0 table 'object_user'
    creating OCEL 2.0 table 'object_team'
    creating OCEL 2.0 table 'object_commit'
Exporting 'ocel2' from raw/Vibe-Trading.duckdb to raw/Vibe-Trading.sqlite...
All done!

In [53]:
from pystackt import create_statistics_views

create_statistics_views(
    quack_db= DUCKDB_PATH_VIBETRADING,
    schema_in="main",
    schema_out="statistics"
)

Overwriting schema 'statistics'
All done! You can explore the statistics on the OCED in schema main, using the views located in schema statistics of your DuckDB database file raw/Vibe-Trading.duckdb.

In [ ]:
from pystackt import *

prepare_graph_data(
    quack_db= DUCKDB_PATH_VIBETRADING,
    schema_in="main",
    schema_out="graph_data_prep"
)

start_visualization_app(
    quack_db= DUCKDB_PATH_VIBETRADING,
    schema="graph_data_prep"
)

In [56]:
import duckdb

quack_db = DUCKDB_PATH_VIBETRADING

with duckdb.connect(quack_db, read_only=True) as con:
    eventsPerobj_df = con.sql("SELECT * FROM graph_data_prep.graph_base_table").df()

eventsPerobj_df

,event_node_id,event_id,event_description,event_type_id,event_type,event_timestamp,event_timestamp_node_id,snapshot_node_id,object_id,object_description,object_type_id,object_type,snapshot_timestamp,snapshot_timestamp_node_id,qualifier_id,qualifier_description,snapshot_dense_rank
0,event_42632,42632,committed (#661),43,committed,2026-07-13 04:39:35,2026-07-13 04:39:35,object_41175_2026-07-13 04:39:35,41175,#661,1,issue,2026-07-13 04:39:35,2026-07-13 04:39:35,20,timeline_event,174
1,event_42640,42640,committed (#661),43,committed,2026-07-13 04:47:58,2026-07-13 04:47:58,object_41175_2026-07-13 04:47:58,41175,#661,1,issue,2026-07-13 04:47:58,2026-07-13 04:47:58,20,timeline_event,175
2,event_42648,42648,committed (#661),43,committed,2026-07-13 04:55:36,2026-07-13 04:55:36,object_41175_2026-07-13 04:55:36,41175,#661,1,issue,2026-07-13 04:55:36,2026-07-13 04:55:36,20,timeline_event,176
3,event_42656,42656,committed (#661),43,committed,2026-07-13 05:01:10,2026-07-13 05:01:10,object_41175_2026-07-13 05:01:10,41175,#661,1,issue,2026-07-13 05:01:10,2026-07-13 05:01:10,20,timeline_event,177
4,event_42664,42664,committed (#661),43,committed,2026-07-13 05:07:59,2026-07-13 05:07:59,object_41175_2026-07-13 05:07:59,41175,#661,1,issue,2026-07-13 05:07:59,2026-07-13 05:07:59,20,timeline_event,178
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31673,event_29881,29881,referenced (#742),4096,referenced,2026-07-30 04:04:05,2026-07-30 04:04:05,object_29839_2026-07-30 04:04:05,29839,#742,1,issue,2026-07-30 04:04:05,2026-07-30 04:04:05,20,timeline_event,9
31674,event_29884,29884,referenced (#742),4096,referenced,2026-07-30 04:04:06,2026-07-30 04:04:06,object_29839_2026-07-30 04:04:06,29839,#742,1,issue,2026-07-30 04:04:06,2026-07-30 04:04:06,20,timeline_event,10
31675,event_30703,30703,committed (#728),43,committed,2026-07-19 00:53:50,2026-07-19 00:53:50,object_30694_2026-07-19 00:53:50,30694,#728,1,issue,2026-07-19 00:53:50,2026-07-19 00:53:50,20,timeline_event,1
31676,event_30698,30698,create #728,31,created,2026-07-19 00:58:59,2026-07-19 00:58:59,object_30694_2026-07-19 00:58:59,30694,#728,1,issue,2026-07-19 00:58:59,2026-07-19 00:58:59,21,created,2
31677,event_30711,30711,merged (#728),16307,merged,2026-07-19 11:40:46,2026-07-19 11:40:46,object_30694_2026-07-19 11:40:46,30694,#728,1,issue,2026-07-19 11:40:46,2026-07-19 11:40:46,20,timeline_event,3

## Finance package #4
OpenBB-finance
OpenBB
https://github.com/OpenBB-finance/OpenBB

In [3]:
import duckdb
import pandas as pd

from pystackt import *

from configToken import GITHUB_ACCESS_TOKEN

from pathlib import Path
import sys

DUCKDB_PATH_OPENBB = "raw/OpenBB.duckdb"
SQLITE_PATH_OPENBB = "raw/OpenBB.sqlite"

In [58]:
from pystackt import get_github_log

get_github_log(
    GITHUB_ACCESS_TOKEN= GITHUB_ACCESS_TOKEN,
    repo_owner="OpenBB-finance",
    repo_name="OpenBB",
    max_issues=None,
    quack_db= DUCKDB_PATH_OPENBB,
    schema="main",
)

Checking if DuckDB database file raw/OpenBB.duckdb is available. New file will be created if it does not exist yet.
    IMPORTANT! Do not connect to DuckDB database file 'raw/OpenBB.duckdb' while this script is running!
    (Or, if you like living on the edge, at least disconnect before the script tries writing to it.)
Start extraction of object-centric event data from all issues of repository OpenBB-finance/OpenBB using GitHub REST API via PyGitHub library.
Status updates will be displayed every 1% progress and every 5 minutes. While you wait, you can read about GitHub API rate limits here: https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api
30-07-2026 13:34    Starting data extraction for approximately 7613 issues ...
30-07-2026 13:34    Extracting and mapping data for issue #7613 done ...0.0% (about 13992.3s remaining)
30-07-2026 13:36    Extracting and mapping data for issue #7503 done ...1.0% (about 13448.6s remaining)
30-07-2026 13:38    Extracting and mapping data for issue #7391 done ...2.0% (about 13715.0s remaining)
30-07-2026 13:39    Extracting and mapping data for issue #7380 done ...2.1% (about 13773.6s remaining)
30-07-2026 13:41    Extracting and mapping data for issue #7295 done ...3.0% (about 13537.4s remaining)
30-07-2026 13:43    Extracting and mapping data for issue #7212 done ...4.0% (about 13246.0s remaining)
30-07-2026 13:44    Extracting and mapping data for issue #7173 done ...4.3% (about 13204.7s remaining)
30-07-2026 13:45    Extracting and mapping data for issue #7119 done ...5.0% (about 13048.9s remaining)
30-07-2026 13:47    Extracting and mapping data for issue #7032 done ...6.0% (about 12807.5s remaining)
30-07-2026 13:49    Extracting and mapping data for issue #6978 done ...6.7% (about 12622.6s remaining)
30-07-2026 13:49    Extracting and mapping data for issue #6949 done ...7.0% (about 12553.9s remaining)
30-07-2026 13:51    Extracting and mapping data for issue #6869 done ...8.0% (about 12200.7s remaining)
30-07-2026 13:53    Extracting and mapping data for issue #6792 done ...9.0% (about 11923.0s remaining)
30-07-2026 13:54    Extracting and mapping data for issue #6779 done ...9.2% (about 11877.8s remaining)
30-07-2026 13:56    Extracting and mapping data for issue #6714 done ...10.0% (about 11986.5s remaining)
30-07-2026 13:58    Extracting and mapping data for issue #6630 done ...11.0% (about 11919.4s remaining)
30-07-2026 13:59    Extracting and mapping data for issue #6618 done ...11.2% (about 11988.1s remaining)
30-07-2026 14:01    Extracting and mapping data for issue #6552 done ...12.0% (about 12024.5s remaining)
30-07-2026 14:03    Extracting and mapping data for issue #6474 done ...13.0% (about 11979.7s remaining)
30-07-2026 14:04    Extracting and mapping data for issue #6468 done ...13.1% (about 11960.7s remaining)
30-07-2026 14:06    Extracting and mapping data for issue #6397 done ...14.0% (about 11871.5s remaining)
30-07-2026 14:08    Extracting and mapping data for issue #6319 done ...15.0% (about 11846.9s remaining)
30-07-2026 14:09    Extracting and mapping data for issue #6313 done ...15.1% (about 11838.7s remaining)
30-07-2026 14:11    Extracting and mapping data for issue #6238 done ...16.0% (about 11753.1s remaining)
30-07-2026 14:13    Extracting and mapping data for issue #6160 done ...17.0% (about 11666.1s remaining)
30-07-2026 14:14    Extracting and mapping data for issue #6154 done ...17.1% (about 11678.9s remaining)
30-07-2026 14:16    Extracting and mapping data for issue #6081 done ...18.0% (about 11711.1s remaining)
30-07-2026 14:19    Extracting and mapping data for issue #6019 done ...18.8% (about 11674.7s remaining)
30-07-2026 14:19    Extracting and mapping data for issue #6002 done ...19.0% (about 11668.9s remaining)
30-07-2026 14:22    Extracting and mapping data for issue #5926 done ...20.0% (about 11647.6s remaining)
30-07-2026 14:24    Extracting and mapping data for issue #5885 done ...20.5% (about 11610.7s remaining)
30-07-2026 14:25    Extracting and mapping data for issue #5848 done ...21.0% (about 11526.5s remaining)
30-07-2026 14:27    Extracting and mapping data for issue #5771 done ...22.0% (about 11357.4s remaining)
30-07-2026 14:29    Extracting and mapping data for issue #5722 done ...22.6% (about 11286.9s remaining)
30-07-2026 14:30    Extracting and mapping data for issue #5693 done ...23.0% (about 11287.7s remaining)

Request GET /repos/OpenBB-finance/OpenBB/issues/5661/timeline failed with 403: Forbidden
Setting next backoff to 161.586707s

30-07-2026 14:34    Extracting and mapping data for issue #5661 done ...23.4% (about 11780.0s remaining)
30-07-2026 14:35    Extracting and mapping data for issue #5616 done ...24.0% (about 11710.8s remaining)
30-07-2026 14:38    Extracting and mapping data for issue #5539 done ...25.0% (about 11629.4s remaining)
30-07-2026 14:39    Extracting and mapping data for issue #5530 done ...25.1% (about 11626.2s remaining)
30-07-2026 14:41    Extracting and mapping data for issue #5460 done ...26.0% (about 11451.0s remaining)
30-07-2026 14:43    Extracting and mapping data for issue #5382 done ...27.0% (about 11254.5s remaining)
30-07-2026 14:44    Extracting and mapping data for issue #5359 done ...27.3% (about 11180.8s remaining)
30-07-2026 14:45    Extracting and mapping data for issue #5303 done ...28.0% (about 11033.6s remaining)
30-07-2026 14:48    Extracting and mapping data for issue #5223 done ...29.0% (about 10952.5s remaining)
30-07-2026 14:49    Extracting and mapping data for issue #5208 done ...29.2% (about 10917.9s remaining)
30-07-2026 14:50    Extracting and mapping data for issue #5147 done ...30.0% (about 10732.3s remaining)
30-07-2026 14:52    Extracting and mapping data for issue #5070 done ...31.0% (about 10498.3s remaining)
30-07-2026 14:54    Extracting and mapping data for issue #5017 done ...31.7% (about 10353.4s remaining)
30-07-2026 14:54    Extracting and mapping data for issue #4990 done ...32.0% (about 10280.1s remaining)
30-07-2026 14:56    Extracting and mapping data for issue #4912 done ...33.0% (about 10075.2s remaining)
30-07-2026 14:58    Extracting and mapping data for issue #4834 done ...34.0% (about 9876.3s remaining)
30-07-2026 14:59    Extracting and mapping data for issue #4830 done ...34.1% (about 9875.0s remaining)
30-07-2026 15:01    Extracting and mapping data for issue #4756 done ...35.0% (about 9713.3s remaining)
30-07-2026 15:03    Extracting and mapping data for issue #4679 done ...36.0% (about 9569.3s remaining)
30-07-2026 15:04    Extracting and mapping data for issue #4670 done ...36.1% (about 9549.2s remaining)
30-07-2026 15:05    Extracting and mapping data for issue #4603 done ...37.0% (about 9376.9s remaining)
30-07-2026 15:08    Extracting and mapping data for issue #4523 done ...38.0% (about 9209.2s remaining)
30-07-2026 15:09    Extracting and mapping data for issue #4494 done ...38.4% (about 9150.9s remaining)
30-07-2026 15:10    Extracting and mapping data for issue #4444 done ...39.0% (about 9037.0s remaining)
30-07-2026 15:12    Extracting and mapping data for issue #4367 done ...40.0% (about 8857.8s remaining)
30-07-2026 15:14    Extracting and mapping data for issue #4313 done ...40.7% (about 8745.8s remaining)
30-07-2026 15:14    Extracting and mapping data for issue #4289 done ...41.0% (about 8694.6s remaining)
30-07-2026 15:17    Extracting and mapping data for issue #4210 done ...42.0% (about 8526.1s remaining)
30-07-2026 15:19    Extracting and mapping data for issue #4139 done ...42.9% (about 8389.8s remaining)
30-07-2026 15:19    Extracting and mapping data for issue #4132 done ...43.0% (about 8373.8s remaining)
30-07-2026 15:21    Extracting and mapping data for issue #4054 done ...44.0% (about 8215.7s remaining)
30-07-2026 15:24    Extracting and mapping data for issue #3976 done ...45.0% (about 8063.8s remaining)
30-07-2026 15:24    Extracting and mapping data for issue #3974 done ...45.0% (about 8058.9s remaining)
30-07-2026 15:26    Extracting and mapping data for issue #3899 done ...46.0% (about 7901.1s remaining)
30-07-2026 15:28    Extracting and mapping data for issue #3818 done ...47.0% (about 7722.2s remaining)
30-07-2026 15:29    Extracting and mapping data for issue #3786 done ...47.4% (about 7662.4s remaining)
30-07-2026 15:30    Extracting and mapping data for issue #3736 done ...48.0% (about 7585.1s remaining)

Request GET /repos/OpenBB-finance/OpenBB/issues/3673/timeline failed with 403: Forbidden
Setting next backoff to 91.91482s

30-07-2026 15:34    Extracting and mapping data for issue #3673 done ...48.8% (about 7548.0s remaining)
30-07-2026 15:34    Extracting and mapping data for issue #3660 done ...49.0% (about 7525.6s remaining)
30-07-2026 15:36    Extracting and mapping data for issue #3584 done ...50.0% (about 7354.4s remaining)
30-07-2026 15:38    Extracting and mapping data for issue #3508 done ...51.0% (about 7191.2s remaining)
30-07-2026 15:39    Extracting and mapping data for issue #3498 done ...51.1% (about 7168.2s remaining)
30-07-2026 15:40    Extracting and mapping data for issue #3431 done ...52.0% (about 7025.9s remaining)
30-07-2026 15:43    Extracting and mapping data for issue #3355 done ...53.0% (about 6876.3s remaining)
30-07-2026 15:44    Extracting and mapping data for issue #3328 done ...53.4% (about 6820.0s remaining)
30-07-2026 15:45    Extracting and mapping data for issue #3278 done ...54.0% (about 6710.5s remaining)
30-07-2026 15:47    Extracting and mapping data for issue #3202 done ...55.0% (about 6548.1s remaining)
30-07-2026 15:49    Extracting and mapping data for issue #3142 done ...55.8% (about 6416.6s remaining)
30-07-2026 15:49    Extracting and mapping data for issue #3126 done ...56.0% (about 6382.3s remaining)
30-07-2026 15:51    Extracting and mapping data for issue #3050 done ...57.0% (about 6213.3s remaining)
30-07-2026 15:53    Extracting and mapping data for issue #2973 done ...58.0% (about 6052.6s remaining)
30-07-2026 15:54    Extracting and mapping data for issue #2945 done ...58.4% (about 5990.5s remaining)
30-07-2026 15:55    Extracting and mapping data for issue #2897 done ...59.0% (about 5890.5s remaining)
30-07-2026 15:57    Extracting and mapping data for issue #2821 done ...60.0% (about 5734.6s remaining)
30-07-2026 15:59    Extracting and mapping data for issue #2758 done ...60.8% (about 5603.1s remaining)
30-07-2026 15:59    Extracting and mapping data for issue #2745 done ...61.0% (about 5577.8s remaining)
30-07-2026 16:01    Extracting and mapping data for issue #2666 done ...62.0% (about 5426.8s remaining)
30-07-2026 16:03    Extracting and mapping data for issue #2590 done ...63.0% (about 5271.0s remaining)
30-07-2026 16:04    Extracting and mapping data for issue #2580 done ...63.1% (about 5253.6s remaining)
30-07-2026 16:06    Extracting and mapping data for issue #2514 done ...64.0% (about 5125.1s remaining)
30-07-2026 16:08    Extracting and mapping data for issue #2437 done ...65.0% (about 4973.6s remaining)
30-07-2026 16:09    Extracting and mapping data for issue #2398 done ...65.5% (about 4894.7s remaining)
30-07-2026 16:09    Starting intermediate save process...
30-07-2026 16:09    Saving object-centric event data extracted from OpenBB-finance/OpenBB to DuckDB database file raw/OpenBB.duckdb, schema main.
Cannot drop schema "main" because it is an internal system entry
    Table object_types (4 records) done.
    Table object_attributes (15 records) done.
    Table objects (53792 records) done.
    Table object_attribute_values (161611 records) done.
    Table event_types (43 records) done.
    Table events (119223 records) done.
    Table event_attributes (43 records) done.
    Table event_attribute_values (16860 records) done.
    Table relation_qualifiers (7 records) done.
    Table event_to_object (291084 records) done.
    Table object_to_object (9995 records) done.
    Table event_to_object_attribute_value (0 records) done.
30-07-2026 16:10    Extracting and mapping data for issue #2361 done ...66.0% (about 4824.1s remaining)
30-07-2026 16:12    Extracting and mapping data for issue #2282 done ...67.0% (about 4677.1s remaining)
30-07-2026 16:14    Extracting and mapping data for issue #2214 done ...67.8% (about 4556.0s remaining)
30-07-2026 16:14    Extracting and mapping data for issue #2200 done ...68.0% (about 4528.5s remaining)
30-07-2026 16:16    Extracting and mapping data for issue #2120 done ...69.0% (about 4383.8s remaining)
30-07-2026 16:18    Extracting and mapping data for issue #2042 done ...70.0% (about 4234.4s remaining)
30-07-2026 16:19    Extracting and mapping data for issue #2031 done ...70.2% (about 4212.2s remaining)
30-07-2026 16:20    Extracting and mapping data for issue #1966 done ...71.0% (about 4083.6s remaining)
30-07-2026 16:23    Extracting and mapping data for issue #1890 done ...72.0% (about 3940.7s remaining)
30-07-2026 16:24    Extracting and mapping data for issue #1851 done ...72.5% (about 3865.1s remaining)
30-07-2026 16:24    Extracting and mapping data for issue #1812 done ...73.0% (about 3790.8s remaining)
30-07-2026 16:26    Extracting and mapping data for issue #1732 done ...74.0% (about 3642.7s remaining)
30-07-2026 16:28    Extracting and mapping data for issue #1634 done ...75.0% (about 3497.1s remaining)
30-07-2026 16:29    Extracting and mapping data for issue #1628 done ...75.1% (about 3485.0s remaining)
30-07-2026 16:30    Extracting and mapping data for issue #1556 done ...76.0% (about 3350.0s remaining)
30-07-2026 16:33    Extracting and mapping data for issue #1479 done ...77.0% (about 3205.7s remaining)

Request GET /repos/OpenBB-finance/OpenBB/issues/1471/timeline failed with 403: Forbidden
Setting next backoff to 54.990706s

30-07-2026 16:34    Extracting and mapping data for issue #1471 done ...77.1% (about 3206.9s remaining)
30-07-2026 16:36    Extracting and mapping data for issue #1403 done ...78.0% (about 3079.1s remaining)
30-07-2026 16:38    Extracting and mapping data for issue #1326 done ...79.0% (about 2938.5s remaining)
30-07-2026 16:39    Extracting and mapping data for issue #1300 done ...79.3% (about 2890.8s remaining)
30-07-2026 16:40    Extracting and mapping data for issue #1249 done ...80.0% (about 2796.7s remaining)
30-07-2026 16:42    Extracting and mapping data for issue #1173 done ...81.0% (about 2653.9s remaining)
30-07-2026 16:44    Extracting and mapping data for issue #1131 done ...81.6% (about 2577.8s remaining)
30-07-2026 16:45    Extracting and mapping data for issue #1096 done ...82.0% (about 2515.7s remaining)
30-07-2026 16:47    Extracting and mapping data for issue #1018 done ...83.0% (about 2374.9s remaining)
30-07-2026 16:49    Extracting and mapping data for issue #969 done ...83.6% (about 2287.7s remaining)
30-07-2026 16:49    Extracting and mapping data for issue #940 done ...84.0% (about 2238.0s remaining)
30-07-2026 16:51    Extracting and mapping data for issue #863 done ...85.0% (about 2091.4s remaining)
30-07-2026 16:53    Extracting and mapping data for issue #782 done ...86.0% (about 1947.6s remaining)
30-07-2026 16:54    Extracting and mapping data for issue #764 done ...86.2% (about 1915.8s remaining)
30-07-2026 16:55    Extracting and mapping data for issue #705 done ...87.0% (about 1805.9s remaining)
30-07-2026 16:57    Extracting and mapping data for issue #579 done ...88.0% (about 1664.2s remaining)
30-07-2026 16:59    Extracting and mapping data for issue #519 done ...88.8% (about 1558.3s remaining)
30-07-2026 16:59    Extracting and mapping data for issue #500 done ...89.0% (about 1522.6s remaining)
30-07-2026 17:01    Extracting and mapping data for issue #420 done ...90.0% (about 1381.3s remaining)
30-07-2026 17:03    Extracting and mapping data for issue #339 done ...91.0% (about 1241.2s remaining)
30-07-2026 17:04    Extracting and mapping data for issue #302 done ...91.4% (about 1180.2s remaining)
30-07-2026 17:05    Extracting and mapping data for issue #256 done ...92.0% (about 1100.9s remaining)
30-07-2026 17:06    Extracting and mapping data for issue #166 done ...93.0% (about 959.4s remaining)
30-07-2026 17:08    Extracting and mapping data for issue #85 done ...94.0% (about 820.3s remaining)
30-07-2026 17:09    Extracting and mapping data for issue #67 done ...94.2% (about 787.5s remaining)
30-07-2026 17:10    Extracting and mapping data for issue #4 done ...95.0% (about 682.5s remaining)
30-07-2026 17:10    Data extraction done! (Final percentage can differ from 100% since it's calculated based on the initial estimate of the number of issues.)
30-07-2026 17:10    Saving object-centric event data extracted from OpenBB-finance/OpenBB to DuckDB database file raw/OpenBB.duckdb, schema main.
Cannot drop schema "main" because it is an internal system entry
    Table object_types (4 records) done.
    Table object_attributes (15 records) done.
    Table objects (74056 records) done.
    Table object_attribute_values (222517 records) done.
    Table event_types (43 records) done.
    Table events (162662 records) done.
    Table event_attributes (43 records) done.
    Table event_attribute_values (26231 records) done.
    Table relation_qualifiers (7 records) done.
    Table event_to_object (398361 records) done.
    Table object_to_object (15148 records) done.
    Table event_to_object_attribute_value (0 records) done.
30-07-2026 17:10    All done!

In [4]:
from pystackt import export_to_ocel2

export_to_ocel2(
    quack_db= DUCKDB_PATH_OPENBB,
    schema_in="main",
    schema_out="ocel2",
    sqlite_db= SQLITE_PATH_OPENBB
)

Overwriting schema 'ocel2'
    creating OCEL 2.0 table 'event'
    creating OCEL 2.0 table 'event_map_type'
    creating OCEL 2.0 table 'event_object'
    creating OCEL 2.0 table 'object_object'
    creating OCEL 2.0 table 'object'
    creating OCEL 2.0 table 'object_map_type'
    creating OCEL 2.0 table 'event_created'
    creating OCEL 2.0 table 'event_committed'
    creating OCEL 2.0 table 'event_commented'
    creating OCEL 2.0 table 'event_closed'
    creating OCEL 2.0 table 'event_cross_referenced'
    creating OCEL 2.0 table 'event_labeled'
    creating OCEL 2.0 table 'event_merged'
    creating OCEL 2.0 table 'event_head_ref_deleted'
    creating OCEL 2.0 table 'event_reviewed'
    creating OCEL 2.0 table 'event_added_to_merge_queue'
    creating OCEL 2.0 table 'event_removed_from_merge_queue'
    creating OCEL 2.0 table 'event_mentioned'
    creating OCEL 2.0 table 'event_subscribed'
    creating OCEL 2.0 table 'event_review_requested'
    creating OCEL 2.0 table 'event_head_ref_force_pushed'
    creating OCEL 2.0 table 'event_connected'
    creating OCEL 2.0 table 'event_assigned'
    creating OCEL 2.0 table 'event_base_ref_changed'
    creating OCEL 2.0 table 'event_copilot_work_started'
    creating OCEL 2.0 table 'event_referenced'
    creating OCEL 2.0 table 'event_renamed'
    creating OCEL 2.0 table 'event_ready_for_review'
    creating OCEL 2.0 table 'event_review_request_removed'
    creating OCEL 2.0 table 'event_auto_merge_enabled'
    creating OCEL 2.0 table 'event_automatic_base_change_succeeded'
    creating OCEL 2.0 table 'event_unlabeled'
    creating OCEL 2.0 table 'event_convert_to_draft'
    creating OCEL 2.0 table 'event_unsubscribed'
    creating OCEL 2.0 table 'event_comment_deleted'
    creating OCEL 2.0 table 'event_reopened'
    creating OCEL 2.0 table 'event_base_ref_deleted'
    creating OCEL 2.0 table 'event_disconnected'
    creating OCEL 2.0 table 'event_unassigned'
    creating OCEL 2.0 table 'event_copilot_work_finished_failure'
    creating OCEL 2.0 table 'event_review_dismissed'
    creating OCEL 2.0 table 'event_auto_merge_disabled'
    creating OCEL 2.0 table 'event_pinned'
    creating OCEL 2.0 table 'event_unpinned'
    creating OCEL 2.0 table 'event_locked'
    creating OCEL 2.0 table 'event_converted_to_discussion'
    creating OCEL 2.0 table 'event_head_ref_restored'
    creating OCEL 2.0 table 'event_milestoned'
    creating OCEL 2.0 table 'event_base_ref_force_pushed'
    creating OCEL 2.0 table 'object_issue'
    creating OCEL 2.0 table 'object_user'
    creating OCEL 2.0 table 'object_team'
    creating OCEL 2.0 table 'object_commit'
Exporting 'ocel2' from raw/OpenBB.duckdb to raw/OpenBB.sqlite...
All done!

In [5]:

from pystackt import create_statistics_views

create_statistics_views(
    quack_db= DUCKDB_PATH_OPENBB,
    schema_in="main",
    schema_out="statistics"
)

Overwriting schema 'statistics'
All done! You can explore the statistics on the OCED in schema main, using the views located in schema statistics of your DuckDB database file raw/OpenBB.duckdb.

In [ ]:
from pystackt import *

prepare_graph_data(
    quack_db= DUCKDB_PATH_OPENBB,
    schema_in="main",
    schema_out="graph_data_prep"
)

start_visualization_app(
    quack_db= DUCKDB_PATH_OPENBB,
    schema="graph_data_prep"
)

In [6]:
import duckdb

quack_db = DUCKDB_PATH_OPENBB

with duckdb.connect(quack_db, read_only=True) as con:
    eventsPerobj_df = con.sql("SELECT * FROM graph_data_prep.graph_base_table").df()

eventsPerobj_df

,event_node_id,event_id,event_description,event_type_id,event_type,event_timestamp,event_timestamp_node_id,snapshot_node_id,object_id,object_description,object_type_id,object_type,snapshot_timestamp,snapshot_timestamp_node_id,qualifier_id,qualifier_description,snapshot_dense_rank
0,event_280441,280441,review_requested (#5621),571,review_requested,2023-10-28 21:05:54,2023-10-28 21:05:54,object_59_2023-10-28 21:05:54,59,user:85772166,2,user,2023-10-28 21:05:54,2023-10-28 21:05:54,22,actor,2734
1,event_280423,280423,create #5621,31,created,2023-10-28 21:05:54,2023-10-28 21:05:54,object_59_2023-10-28 21:05:54,59,user:85772166,2,user,2023-10-28 21:05:54,2023-10-28 21:05:54,21,created,2734
2,event_280446,280446,review_requested (#5621),571,review_requested,2023-10-28 21:05:55,2023-10-28 21:05:55,object_59_2023-10-28 21:05:55,59,user:85772166,2,user,2023-10-28 21:05:55,2023-10-28 21:05:55,22,actor,2735
3,event_280486,280486,labeled (#5621),202,labeled,2023-10-28 23:56:21,2023-10-28 23:56:21,object_59_2023-10-28 23:56:21,59,user:85772166,2,user,2023-10-28 23:56:21,2023-10-28 23:56:21,22,actor,2736
4,event_280489,280489,labeled (#5621),202,labeled,2023-10-28 23:56:21,2023-10-28 23:56:21,object_59_2023-10-28 23:56:21,59,user:85772166,2,user,2023-10-28 23:56:21,2023-10-28 23:56:21,22,actor,2736
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
398356,event_460765,460765,committed (#4341),43,committed,2023-03-28 18:54:16,2023-03-28 18:54:16,object_460044_2023-03-28 18:54:16,460044,#4341,1,issue,2023-03-28 18:54:16,2023-03-28 18:54:16,20,timeline_event,96
398357,event_460773,460773,committed (#4341),43,committed,2023-03-28 19:05:53,2023-03-28 19:05:53,object_460044_2023-03-28 19:05:53,460044,#4341,1,issue,2023-03-28 19:05:53,2023-03-28 19:05:53,20,timeline_event,97
398358,event_460781,460781,committed (#4341),43,committed,2023-03-28 20:26:24,2023-03-28 20:26:24,object_460044_2023-03-28 20:26:24,460044,#4341,1,issue,2023-03-28 20:26:24,2023-03-28 20:26:24,20,timeline_event,98
398359,event_460789,460789,committed (#4341),43,committed,2023-03-28 20:28:35,2023-03-28 20:28:35,object_460044_2023-03-28 20:28:35,460044,#4341,1,issue,2023-03-28 20:28:35,2023-03-28 20:28:35,20,timeline_event,99
398360,event_460797,460797,committed (#4341),43,committed,2023-03-28 20:31:56,2023-03-28 20:31:56,object_460044_2023-03-28 20:31:56,460044,#4341,1,issue,2023-03-28 20:31:56,2023-03-28 20:31:56,20,timeline_event,100

## Finance package #5
AI4Finance-Foundation
FinRL
https://github.com/AI4Finance-Foundation/FinRL

In [5]:
import duckdb
import pandas as pd

from pystackt import *

from configToken import GITHUB_ACCESS_TOKEN

from pathlib import Path
import sys

DUCKDB_PATH_FinRL = "raw/FinRL.duckdb"
SQLITE_PATH_FinRL = "raw/FinRL.sqlite"

In [6]:

from pystackt import get_github_log

get_github_log(
    GITHUB_ACCESS_TOKEN= GITHUB_ACCESS_TOKEN,
    repo_owner="AI4Finance-Foundation",
    repo_name="FinRL",
    max_issues=None,
    quack_db= DUCKDB_PATH_FinRL,
    schema="main",
)

Checking if DuckDB database file raw/FinRL.duckdb is available. New file will be created if it does not exist yet.
    IMPORTANT! Do not connect to DuckDB database file 'raw/FinRL.duckdb' while this script is running!
    (Or, if you like living on the edge, at least disconnect before the script tries writing to it.)
Start extraction of object-centric event data from all issues of repository AI4Finance-Foundation/FinRL using GitHub REST API via PyGitHub library.
Status updates will be displayed every 1% progress and every 5 minutes. While you wait, you can read about GitHub API rate limits here: https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api
31-07-2026 16:53    Starting data extraction for approximately 1430 issues ...
31-07-2026 16:53    Extracting and mapping data for issue #1430 done ...0.1% (about 2028.8s remaining)
31-07-2026 16:54    Extracting and mapping data for issue #1374 done ...1.0% (about 3330.8s remaining)
31-07-2026 16:54    Extracting and mapping data for issue #1349 done ...2.0% (about 2685.6s remaining)
31-07-2026 16:54    Extracting and mapping data for issue #1326 done ...3.0% (about 2483.4s remaining)
31-07-2026 16:55    Extracting and mapping data for issue #1302 done ...4.1% (about 2363.8s remaining)
31-07-2026 16:55    Extracting and mapping data for issue #1283 done ...5.0% (about 2271.2s remaining)
31-07-2026 16:56    Extracting and mapping data for issue #1261 done ...6.0% (about 2206.5s remaining)
31-07-2026 16:56    Extracting and mapping data for issue #1234 done ...7.1% (about 2243.1s remaining)
31-07-2026 16:56    Extracting and mapping data for issue #1206 done ...8.0% (about 2187.9s remaining)
31-07-2026 16:57    Extracting and mapping data for issue #1183 done ...9.0% (about 2144.8s remaining)
31-07-2026 16:57    Extracting and mapping data for issue #1158 done ...10.0% (about 2103.2s remaining)
31-07-2026 16:57    Extracting and mapping data for issue #1123 done ...11.0% (about 2069.0s remaining)
31-07-2026 16:58    Extracting and mapping data for issue #1101 done ...12.0% (about 2020.5s remaining)
31-07-2026 16:58    Extracting and mapping data for issue #1071 done ...13.0% (about 1993.1s remaining)
31-07-2026 16:58    Extracting and mapping data for issue #1064 done ...13.1% (about 1991.5s remaining)
31-07-2026 16:58    Extracting and mapping data for issue #1039 done ...14.1% (about 1952.7s remaining)
31-07-2026 16:59    Extracting and mapping data for issue #999 done ...15.0% (about 1930.5s remaining)
31-07-2026 16:59    Extracting and mapping data for issue #959 done ...16.0% (about 1903.9s remaining)
31-07-2026 17:00    Extracting and mapping data for issue #933 done ...17.1% (about 1866.4s remaining)
31-07-2026 17:00    Extracting and mapping data for issue #913 done ...18.0% (about 1829.8s remaining)
31-07-2026 17:00    Extracting and mapping data for issue #893 done ...19.0% (about 1795.2s remaining)
31-07-2026 17:01    Extracting and mapping data for issue #871 done ...20.0% (about 1767.0s remaining)
31-07-2026 17:01    Extracting and mapping data for issue #850 done ...21.0% (about 1738.3s remaining)
31-07-2026 17:01    Extracting and mapping data for issue #834 done ...22.0% (about 1713.9s remaining)
31-07-2026 17:02    Extracting and mapping data for issue #819 done ...23.0% (about 1686.0s remaining)
31-07-2026 17:02    Extracting and mapping data for issue #801 done ...24.1% (about 1663.5s remaining)
31-07-2026 17:02    Extracting and mapping data for issue #787 done ...25.0% (about 1652.7s remaining)
31-07-2026 17:03    Extracting and mapping data for issue #767 done ...26.0% (about 1627.8s remaining)
31-07-2026 17:03    Extracting and mapping data for issue #734 done ...27.1% (about 1597.2s remaining)
31-07-2026 17:03    Extracting and mapping data for issue #721 done ...27.4% (about 1590.8s remaining)
31-07-2026 17:03    Extracting and mapping data for issue #704 done ...28.0% (about 1573.4s remaining)
31-07-2026 17:04    Extracting and mapping data for issue #684 done ...29.0% (about 1551.0s remaining)
31-07-2026 17:04    Extracting and mapping data for issue #667 done ...30.0% (about 1529.4s remaining)
31-07-2026 17:05    Extracting and mapping data for issue #650 done ...31.0% (about 1522.3s remaining)
31-07-2026 17:05    Extracting and mapping data for issue #635 done ...32.0% (about 1499.7s remaining)
31-07-2026 17:05    Extracting and mapping data for issue #621 done ...33.0% (about 1473.1s remaining)
31-07-2026 17:06    Extracting and mapping data for issue #596 done ...34.1% (about 1447.2s remaining)
31-07-2026 17:06    Extracting and mapping data for issue #579 done ...35.0% (about 1427.7s remaining)
31-07-2026 17:06    Extracting and mapping data for issue #555 done ...36.0% (about 1409.4s remaining)
31-07-2026 17:07    Extracting and mapping data for issue #539 done ...37.1% (about 1385.1s remaining)
31-07-2026 17:07    Extracting and mapping data for issue #521 done ...38.0% (about 1364.1s remaining)
31-07-2026 17:07    Extracting and mapping data for issue #501 done ...39.0% (about 1340.8s remaining)
31-07-2026 17:08    Extracting and mapping data for issue #482 done ...40.0% (about 1319.9s remaining)
31-07-2026 17:08    Extracting and mapping data for issue #465 done ...41.0% (about 1291.9s remaining)
31-07-2026 17:08    Extracting and mapping data for issue #464 done ...41.1% (about 1290.6s remaining)
31-07-2026 17:08    Extracting and mapping data for issue #450 done ...42.0% (about 1268.8s remaining)
31-07-2026 17:09    Extracting and mapping data for issue #434 done ...43.0% (about 1244.8s remaining)
31-07-2026 17:09    Extracting and mapping data for issue #417 done ...44.1% (about 1219.7s remaining)
31-07-2026 17:10    Extracting and mapping data for issue #401 done ...45.0% (about 1198.0s remaining)
31-07-2026 17:10    Extracting and mapping data for issue #381 done ...46.0% (about 1175.3s remaining)
31-07-2026 17:10    Extracting and mapping data for issue #366 done ...47.1% (about 1150.2s remaining)
31-07-2026 17:11    Extracting and mapping data for issue #352 done ...48.0% (about 1127.7s remaining)
31-07-2026 17:11    Extracting and mapping data for issue #336 done ...49.0% (about 1104.5s remaining)
31-07-2026 17:11    Extracting and mapping data for issue #322 done ...50.0% (about 1080.5s remaining)
31-07-2026 17:12    Extracting and mapping data for issue #304 done ...51.0% (about 1055.8s remaining)
31-07-2026 17:12    Extracting and mapping data for issue #290 done ...52.0% (about 1034.0s remaining)
31-07-2026 17:12    Extracting and mapping data for issue #272 done ...53.0% (about 1013.1s remaining)
31-07-2026 17:13    Extracting and mapping data for issue #257 done ...54.1% (about 988.8s remaining)
31-07-2026 17:13    Extracting and mapping data for issue #243 done ...55.0% (about 966.3s remaining)
31-07-2026 17:13    Extracting and mapping data for issue #229 done ...55.9% (about 945.6s remaining)
31-07-2026 17:13    Extracting and mapping data for issue #228 done ...56.0% (about 944.2s remaining)
31-07-2026 17:14    Extracting and mapping data for issue #205 done ...57.1% (about 923.4s remaining)
31-07-2026 17:14    Extracting and mapping data for issue #186 done ...58.0% (about 902.4s remaining)
31-07-2026 17:14    Extracting and mapping data for issue #171 done ...59.0% (about 881.1s remaining)
31-07-2026 17:15    Extracting and mapping data for issue #157 done ...60.0% (about 860.0s remaining)
31-07-2026 17:15    Extracting and mapping data for issue #142 done ...61.0% (about 837.1s remaining)
31-07-2026 17:15    Extracting and mapping data for issue #125 done ...62.0% (about 816.5s remaining)
31-07-2026 17:16    Extracting and mapping data for issue #109 done ...63.0% (about 795.2s remaining)
31-07-2026 17:16    Extracting and mapping data for issue #94 done ...64.1% (about 772.2s remaining)
31-07-2026 17:16    Extracting and mapping data for issue #80 done ...65.0% (about 750.6s remaining)
31-07-2026 17:17    Extracting and mapping data for issue #66 done ...66.0% (about 728.9s remaining)
31-07-2026 17:17    Extracting and mapping data for issue #51 done ...67.1% (about 706.8s remaining)
31-07-2026 17:17    Extracting and mapping data for issue #37 done ...68.0% (about 685.2s remaining)
31-07-2026 17:18    Extracting and mapping data for issue #23 done ...69.0% (about 662.9s remaining)
31-07-2026 17:18    Extracting and mapping data for issue #8 done ...70.0% (about 641.5s remaining)
31-07-2026 17:18    Extracting and mapping data for issue #5 done ...70.2% (about 636.5s remaining)
31-07-2026 17:18    Data extraction done! (Final percentage can differ from 100% since it's calculated based on the initial estimate of the number of issues.)
31-07-2026 17:18    Saving object-centric event data extracted from AI4Finance-Foundation/FinRL to DuckDB database file raw/FinRL.duckdb, schema main.
Cannot drop schema "main" because it is an internal system entry
    Table object_types (4 records) done.
    Table object_attributes (15 records) done.
    Table objects (4858 records) done.
    Table object_attribute_values (14884 records) done.
    Table event_types (27 records) done.
    Table events (9630 records) done.
    Table event_attributes (27 records) done.
    Table event_attribute_values (3006 records) done.
    Table relation_qualifiers (7 records) done.
    Table event_to_object (22530 records) done.
    Table object_to_object (1194 records) done.
    Table event_to_object_attribute_value (0 records) done.
31-07-2026 17:18    All done!

In [7]:
from pystackt import export_to_ocel2

export_to_ocel2(
    quack_db= DUCKDB_PATH_FinRL,
    schema_in="main",
    schema_out="ocel2",
    sqlite_db= SQLITE_PATH_FinRL
)

Overwriting schema 'ocel2'
    creating OCEL 2.0 table 'event'
    creating OCEL 2.0 table 'event_map_type'
    creating OCEL 2.0 table 'event_object'
    creating OCEL 2.0 table 'object_object'
    creating OCEL 2.0 table 'object'
    creating OCEL 2.0 table 'object_map_type'
    creating OCEL 2.0 table 'event_created'
    creating OCEL 2.0 table 'event_committed'
    creating OCEL 2.0 table 'event_closed'
    creating OCEL 2.0 table 'event_ready_for_review'
    creating OCEL 2.0 table 'event_merged'
    creating OCEL 2.0 table 'event_assigned'
    creating OCEL 2.0 table 'event_cross_referenced'
    creating OCEL 2.0 table 'event_head_ref_force_pushed'
    creating OCEL 2.0 table 'event_commented'
    creating OCEL 2.0 table 'event_mentioned'
    creating OCEL 2.0 table 'event_subscribed'
    creating OCEL 2.0 table 'event_referenced'
    creating OCEL 2.0 table 'event_renamed'
    creating OCEL 2.0 table 'event_unsubscribed'
    creating OCEL 2.0 table 'event_base_ref_changed'
    creating OCEL 2.0 table 'event_head_ref_deleted'
    creating OCEL 2.0 table 'event_reviewed'
    creating OCEL 2.0 table 'event_head_ref_restored'
    creating OCEL 2.0 table 'event_labeled'
    creating OCEL 2.0 table 'event_review_requested'
    creating OCEL 2.0 table 'event_unlabeled'
    creating OCEL 2.0 table 'event_reopened'
    creating OCEL 2.0 table 'event_comment_deleted'
    creating OCEL 2.0 table 'event_unassigned'
    creating OCEL 2.0 table 'event_convert_to_draft'
    creating OCEL 2.0 table 'event_base_ref_deleted'
    creating OCEL 2.0 table 'event_connected'
    creating OCEL 2.0 table 'object_issue'
    creating OCEL 2.0 table 'object_user'
    creating OCEL 2.0 table 'object_team'
    creating OCEL 2.0 table 'object_commit'
Exporting 'ocel2' from raw/FinRL.duckdb to raw/FinRL.sqlite...
All done!

In [8]:
from pystackt import create_statistics_views

create_statistics_views(
    quack_db= DUCKDB_PATH_FinRL,
    schema_in="main",
    schema_out="statistics"
)

Overwriting schema 'statistics'
All done! You can explore the statistics on the OCED in schema main, using the views located in schema statistics of your DuckDB database file raw/FinRL.duckdb.

In [ ]:
from pystackt import *

prepare_graph_data(
    quack_db= DUCKDB_PATH_FinRL,
    schema_in="main",
    schema_out="graph_data_prep"
)

start_visualization_app(
    quack_db= DUCKDB_PATH_FinRL,
    schema="graph_data_prep"
)

In [10]:
import duckdb

quack_db = DUCKDB_PATH_FinRL

with duckdb.connect(quack_db, read_only=True) as con:
    eventsPerobj_df = con.sql("SELECT * FROM graph_data_prep.graph_base_table").df()

eventsPerobj_df

,event_node_id,event_id,event_description,event_type_id,event_type,event_timestamp,event_timestamp_node_id,snapshot_node_id,object_id,object_description,object_type_id,object_type,snapshot_timestamp,snapshot_timestamp_node_id,qualifier_id,qualifier_description,snapshot_dense_rank
0,event_54,54,committed (#1430),43,committed,2026-07-18 23:51:17,2026-07-18 23:51:17,object_56_2026-07-18 23:51:17,56,sha:35706d84290cc8de291317e547e7a1fcd2051e51,4,commit,2026-07-18 23:51:17,2026-07-18 23:51:17,20,timeline_event,1
1,event_70,70,committed (#1430),43,committed,2026-07-19 15:46:27,2026-07-19 15:46:27,object_72_2026-07-19 15:46:27,72,sha:74380ee545534089ea541015ac4615300c0ee007,4,commit,2026-07-19 15:46:27,2026-07-19 15:46:27,20,timeline_event,1
2,event_262,262,create #1409,31,created,2026-04-03 10:03:55,2026-04-03 10:03:55,object_265_2026-04-03 10:03:55,265,user:76570345,2,user,2026-04-03 10:03:55,2026-04-03 10:03:55,21,created,1
3,event_289,289,closed (#1409),110,closed,2026-04-03 10:32:00,2026-04-03 10:32:00,object_265_2026-04-03 10:32:00,265,user:76570345,2,user,2026-04-03 10:32:00,2026-04-03 10:32:00,22,actor,2
4,event_281,281,committed (#1409),43,committed,2026-04-03 10:04:09,2026-04-03 10:04:09,object_283_2026-04-03 10:04:09,283,sha:aeda233c3bb3ede46d792349cbc223af13105b88,4,commit,2026-04-03 10:04:09,2026-04-03 10:04:09,20,timeline_event,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22525,event_55405,55405,committed (#22),43,committed,2020-12-31 01:25:31,2020-12-31 01:25:31,object_55396_2020-12-31 01:25:31,55396,#22,1,issue,2020-12-31 01:25:31,2020-12-31 01:25:31,20,timeline_event,1
22526,event_55400,55400,create #22,31,created,2020-12-31 01:26:24,2020-12-31 01:26:24,object_55396_2020-12-31 01:26:24,55396,#22,1,issue,2020-12-31 01:26:24,2020-12-31 01:26:24,21,created,2
22527,event_55413,55413,closed (#22),110,closed,2020-12-31 01:31:43,2020-12-31 01:31:43,object_55396_2020-12-31 01:31:43,55396,#22,1,issue,2020-12-31 01:31:43,2020-12-31 01:31:43,20,timeline_event,3
22528,event_55504,55504,create #18,31,created,2020-12-28 06:08:42,2020-12-28 06:08:42,object_55507_2020-12-28 06:08:42,55507,user:29737079,2,user,2020-12-28 06:08:42,2020-12-28 06:08:42,21,created,1
22529,event_55580,55580,create #16,31,created,2020-12-21 16:42:14,2020-12-21 16:42:14,object_55583_2020-12-21 16:42:14,55583,user:73476851,2,user,2020-12-21 16:42:14,2020-12-21 16:42:14,21,created,1